### PR TITLE
Bug/#335 error when deleting account

### LINKED ISSUE #335: Make accounts deletable
Currently, when deleting an account, an error occurs.

### PR DESCRIPTION
**Pull request by MartinBuessemeyer**
# Resolves #335

This PR removes the bug that users cannot be deleted.

Acceptance Criteria:
- [ ] users can be delete without an error

Testing steps:
- automatic: execute the tests
- manual: create a new account, go to account settings and delete the account 

Steps needed for migration:
- `bundle exec rails db:migrate RAILS_ENV=development && bundle exec rails db:migrate RAILS_ENV=test && bundle exec rails db:seed`

---

Definition Of Done:
- [x] [Class-Diagram](https://www.lucidchart.com/invitations/accept/705a122b-58a9-4dfa-8b16-c936bc0a46bc) updated

### CODE REVIEW

File: spec/models/user_spec.rb [hunk 1]
```diff
@@ -51,4 +51,8 @@
     @user.upvoted_questions << question1
     @user.upvoted_questions << question2
   end
+
+  it "can be destroyed" do
+    expect { @user.destroy }.to_not raise_error
+  end
```
Comment (WorldofJARcraft) [inline spec/models/user_spec.rb]: This only tests destroying a user who has no relationships to lectures, polls, ... Add additional tests where user who are referenced by uploaded_files, lectures, courses, polls and questions are deleted.

Comment (adrianjost) [reply spec/models/user_spec.rb]: @WorldofJARcraft better now? I have added 3 more test cases.
